# BASTION - Caldera-Wazuh Integration Plugin Configuration
# 기본 설정은 default.yml을 따르고, BASTION 플러그인을 추가로 활성화

crypt_salt: b8d2f0a3e1c9d7b5a4f3e2d1c9b8a7f6e5d4c3b2a1908f7e6d5c4b3a29180706f
encryption_key: ADMIN123

# API 키 설정
api_key_blue: BLUEADMIN123
api_key_red: REDADMIN123

# 플러그인 목록 (BASTION 추가)
plugins:
  - sandcat      # C2 에이전트
  - stockpile    # 기본 능력 집합
  - bastion      # Caldera-Wazuh Integration Plugin

# 사용자 계정
users:
  red:
    red: redpassword
  blue:
    blue: bluepassword

# Wazuh 연동 설정 (환경 변수로도 설정 가능)
# 이 값들은 docker-compose.yml의 환경 변수가 우선됩니다
bastion:
  wazuh:
    manager_url: https://wazuh.manager:55000
    indexer_url: http://elasticsearch:9200
    manager_username: wazuh
    manager_password: MyS3cur3P@ssw0rd!
    indexer_username: elastic
    indexer_password: Kimdong2024
    verify_ssl: false

  # 상관관계 엔진 설정
  correlation:
    enabled: true
    time_window_seconds: 300
    min_confidence_score: 0.7

  # 대시보드 업데이트 간격 (초)
  refresh_interval: 5

  # 로깅 레벨
  log_level: INFO

# 서버 설정
host: 0.0.0.0
port: 8888

# 기본 planner
objects.planners.default: atomic
